name: 🐛 Bug Report
description: Report a bug or issue
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: ['rjbizsolution23-wq']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: dropdown
    id: repository
    attributes:
      label: Repository
      description: Which repository is this bug related to?
      options:
        - rj-business-solutions-main
        - agi-prompt-engineering
        - data-engineering-pipelines
        - fullstack-development-templates
        - ai-ml-fine-tuning-suite
        - cloud-cybersecurity-tools
        - client-project-templates
        - rj-business-automation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Describe the bug...
    validations:
      required: true
